# DeepCAD minimial implementation

In [1]:
# venv: conda activate myenc
import json
import h5py
import os.path
import matplotlib.pyplot as plt
DATA_DIR = 'data'

In [174]:
with open('../DeepCAD/data/train_val_test_split.json', 'r') as file:
    data = json.load(file)

In [175]:
print(os.getcwd())

/Users/saidharb/Documents/LocalDocuments/Master-Thesis/Point-Cloud-Reconstruction/code


In [176]:
data.keys()

dict_keys(['train', 'validation', 'test'])

In [177]:
test_data = data['test']
train_data = data['train']
val_data = data['validation']

In [178]:
len(train_data)/(len(train_data) + len(val_data) + len(test_data)) 

0.9046331309821699

In [179]:
for i,a in enumerate(test_data):
    if a == '0025/00250456':
        print(i)

0


In [180]:
file_name = '../DeepCAD/data/cad_vec/0025/00250456.h5'
with h5py.File(file_name, 'r') as f:
    print(f.keys())
    for key in f.keys():
        print(f"key - {key}: {f[key]}")
        data = f[key][()]
        print(data)


<KeysViewHDF5 ['vec']>
key - vec: <HDF5 dataset "vec": shape (7, 17), type "<i8">
[[  4  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  5  -1  -1  -1  -1  -1 192  64 192  32 128  32 192 224 128   0   1]
 [  3  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]]


In [181]:
result_file_name = '../DeepCAD/proj_log/pretrained/results/test_1000/00250456_vec.h5'
with h5py.File(result_file_name, 'r') as f:
    print(f.keys())
    for key in f.keys():
        print(f"key - {key}: {f[key]}")
        data = f[key][()]
        print(data)

<KeysViewHDF5 ['gt_vec', 'out_vec']>
key - gt_vec: <HDF5 dataset "gt_vec": shape (6, 17), type "<i8">
[[  4  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  5  -1  -1  -1  -1  -1 192  64 192  32 128  32 192 224 128   0   1]]
key - out_vec: <HDF5 dataset "out_vec": shape (6, 17), type "<i8">
[[  4  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 223  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  5  -1  -1  -1  -1  -1 192  64 192  32 128  32

## Start

These are like the overall (macro) parameters and settings:

In [182]:
Arsch = [2]*3

In [183]:
a = [*Arsch]
a

[2, 2, 2]

In [184]:
import numpy as np

ALL_COMMANDS = ['Line', 'Arc', 'Circle', 'EOS', 'SOL', 'Ext']
LINE_IDX = ALL_COMMANDS.index('Line')
ARC_IDX = ALL_COMMANDS.index('Arc')
CIRCLE_IDX = ALL_COMMANDS.index('Circle')
EOS_IDX = ALL_COMMANDS.index('EOS')
SOL_IDX = ALL_COMMANDS.index('SOL')
EXT_IDX = ALL_COMMANDS.index('Ext')

EXTRUDE_OPERATIONS = ["NewBodyFeatureOperation", "JoinFeatureOperation",
                      "CutFeatureOperation", "IntersectFeatureOperation"]
EXTENT_TYPE = ["OneSideFeatureExtentType", "SymmetricFeatureExtentType",
               "TwoSidesFeatureExtentType"]

PAD_VAL = -1
N_ARGS_SKETCH = 5 # sketch parameters: x, y, alpha, f, r
N_ARGS_PLANE = 3 # sketch plane orientation: theta, phi, gamma
N_ARGS_TRANS = 4 # sketch plane origin + sketch bbox size: p_x, p_y, p_z, s
N_ARGS_EXT_PARAM = 4 # extrusion parameters: e1, e2, b, u
N_ARGS_EXT = N_ARGS_PLANE + N_ARGS_TRANS + N_ARGS_EXT_PARAM
N_ARGS = N_ARGS_SKETCH + N_ARGS_EXT

SOL_VEC = np.array([SOL_IDX, *([PAD_VAL] * N_ARGS)])
EOS_VEC = np.array([EOS_IDX, *([PAD_VAL] * N_ARGS)])

CMD_ARGS_MASK = np.array([[1, 1, 0, 0, 0, *[0]*N_ARGS_EXT],  # line
                          [1, 1, 1, 1, 0, *[0]*N_ARGS_EXT],  # arc
                          [1, 1, 0, 0, 1, *[0]*N_ARGS_EXT],  # circle
                          [0, 0, 0, 0, 0, *[0]*N_ARGS_EXT],  # EOS
                          [0, 0, 0, 0, 0, *[0]*N_ARGS_EXT],  # SOL
                          [*[0]*N_ARGS_SKETCH, *[1]*N_ARGS_EXT]]) # Extrude

NORM_FACTOR = 0.75 # scale factor for normalization to prevent overflow during augmentation

MAX_N_EXT = 10 # maximum number of extrusion
MAX_N_LOOPS = 6 # maximum number of loops per sketch
MAX_N_CURVES = 15 # maximum number of curves per loop
MAX_TOTAL_LEN = 60 # maximum cad sequence length
ARGS_DIM = 256


## ConfigAE

These are the specific configurations of the AutoEncoder

In [185]:
import os
import sys

# Add the DeepCAD directory to sys.path
sys.path.append('/Users/saidharb/Documents/LocalDocuments/Master-Thesis/Point-Cloud-Reconstruction/DeepCAD')
from utils import ensure_dirs
import argparse
import json
import shutil

In [186]:
print(len(ALL_COMMANDS))

6


In [187]:
class ConfigAE(object):
    def __init__(self, phase):
        self.is_train = phase == "train"
        self.set_configuration()
        parser, args = self.parse()
        
        # set as attributes
        print("----Experiment Configuration-----")
        for k, v in args.__dict__.items():
            print("{0:20}".format(k), v)
            self.__setattr__(k, v)

        # experiment paths
        self.exp_dir = os.path.join(self.proj_dir, self.exp_name)
        
##############   We omit Training first ###########################        
#        if phase == "train" and args.cont is not True and os.path.exists(self.exp_dir):
 #           response = input('Experiment log/model already exists, overwrite? (y/n) ')
  #          if response != 'y':
   #             exit()
    #        shutil.rmtree(self.exp_dir)

        self.log_dir = os.path.join(self.exp_dir, 'log')
        self.model_dir = os.path.join(self.exp_dir, 'model')
        ensure_dirs([self.log_dir, self.model_dir])

        # save this configuration
        if self.is_train:
            with open('{}/config.txt'.format(self.exp_dir), 'w') as f:
                json.dump(args.__dict__, f, indent=2)

    def set_configuration(self):
        self.args_dim = ARGS_DIM # 256
        self.n_args = N_ARGS
        self.n_commands = len(ALL_COMMANDS)  # line, arc, circle, EOS, SOS, extrusion

        self.n_layers = 4                # Number of Encoder blocks
        self.n_layers_decode = 4         # Number of Decoder blocks
        self.n_heads = 8                 # Transformer config: number of heads
        self.dim_feedforward = 512       # Transformer config: FF dimensionality
        self.d_model = 256               # Transformer config: model dimensionality
        self.dropout = 0.1                # Dropout rate used in basic layers and Transformers
        self.dim_z = 256                 # Latent vector dimensionality
        self.use_group_emb = True

        self.max_n_ext = MAX_N_EXT
        self.max_n_loops = MAX_N_LOOPS
        self.max_n_curves = MAX_N_CURVES

        self.max_num_groups = 30
        self.max_total_len = MAX_TOTAL_LEN

        self.loss_weights = {
            "loss_cmd_weight": 1.0,
            "loss_args_weight": 2.0
        }

    def parse(self):
        """initiaize argument parser. Define default hyperparameters and collect from command-line arguments."""
        parser = argparse.ArgumentParser()

        parser.add_argument('--proj_dir', type=str, default="proj_log", help="path to project folder where models and logs will be saved")
        parser.add_argument('--data_root', type=str, default="data", help="path to source data folder")
        parser.add_argument('--exp_name', type=str, default=os.getcwd().split('/')[-1], help="name of this experiment")
        parser.add_argument('-g', '--gpu_ids', type=str, default='0', help="gpu to use, e.g. 0  0,1,2. CPU not supported.")
        parser.add_argument('--batch_size', type=int, default=512, help="batch size")
        parser.add_argument('--num_workers', type=int, default=8, help="number of workers for data loading")
        parser.add_argument('--nr_epochs', type=int, default=1000, help="total number of epochs to train")
        parser.add_argument('--lr', type=float, default=1e-3, help="initial learning rate")
        parser.add_argument('--grad_clip', type=float, default=1.0, help="initial learning rate")
        parser.add_argument('--warmup_step', type=int, default=2000, help="step size for learning rate warm up")
        parser.add_argument('--continue', dest='cont',  action='store_true', help="continue training from checkpoint")
        parser.add_argument('--ckpt', type=str, default='latest', required=False, help="desired checkpoint to restore")
        parser.add_argument('--vis', action='store_true', default=False, help="visualize output in training")
        parser.add_argument('--save_frequency', type=int, default=500, help="save models every x epochs")
        parser.add_argument('--val_frequency', type=int, default=10, help="run validation every x iterations")
        parser.add_argument('--vis_frequency', type=int, default=2000, help="visualize output every x iterations")
        parser.add_argument('--augment', action='store_true', help="use random data augmentation")
        
        if not self.is_train:
            parser.add_argument('-m', '--mode', type=str, choices=['rec', 'enc', 'dec'])
            parser.add_argument('-o', '--outputs', type=str, default=None)
            parser.add_argument('--z_path', type=str, default=None)
        
        args = parser.parse_args([
            '--proj_dir', '../DeepCAD/proj_log',
            '--data_root', '../DeepCAD/data',
            '--exp_name', 'pretrained',
            '--batch_size', '512',  # Convert to string
            '--nr_epochs', '1000',  # Convert to string
            '--lr', '1e-3',         # Convert to string
            '--grad_clip', '1.0',   # Convert to string
            '--warmup_step', '2000',# Convert to string
            '--ckpt', '1000',
            '--save_frequency', '500', # Convert to string
            '--val_frequency', '10',   # Convert to string
            '--vis_frequency', '2000',  # Convert to string
            '--mode', 'rec',
            '--num_workers', 0,
        ])
        return parser, args


## CADTransformer

In [188]:
from tqdm import tqdm
from dataset.cad_dataset import get_dataloader
from utils import ensure_dir
import torch
import numpy as np
import os
import h5py
from cadlib.macro import EOS_IDX
import torch.nn as nn

In [189]:
class Bottleneck(nn.Module):
    def __init__(self, cfg):
        super(Bottleneck, self).__init__()

        self.bottleneck = nn.Sequential(nn.Linear(cfg.d_model, cfg.dim_z),
                                        nn.Tanh())

    def forward(self, z):
        return self.bottleneck(z)

In [190]:
class FCN(nn.Module):
    def __init__(self, d_model, n_commands, n_args, args_dim=256):
        super().__init__()

        self.n_args = n_args
        self.args_dim = args_dim

        self.command_fcn = nn.Linear(d_model, n_commands)
        self.args_fcn = nn.Linear(d_model, n_args * args_dim)

    def forward(self, out):
        S, N, _ = out.shape

        command_logits = self.command_fcn(out)  # Shape [S, N, n_commands]

        args_logits = self.args_fcn(out)  # Shape [S, N, n_args * args_dim]
        args_logits = args_logits.reshape(S, N, self.n_args, self.args_dim)  # Shape [S, N, n_args, args_dim]

        return command_logits, args_logits

In [191]:
class ConstEmbedding(nn.Module):
    """learned constant embedding"""
    def __init__(self, cfg, seq_len):
        super().__init__()

        self.d_model = cfg.d_model
        self.seq_len = seq_len

        self.PE = PositionalEncodingLUT(cfg.d_model, max_len=seq_len)

    def forward(self, z):
        N = z.size(1)
        src = self.PE(z.new_zeros(self.seq_len, N, self.d_model))
        return src

In [192]:
class CADEmbedding(nn.Module):
    """Embedding: positional embed + command embed + parameter embed + group embed (optional)"""
    def __init__(self, cfg, seq_len, use_group=False, group_len=None):
        super().__init__()

        self.command_embed = nn.Embedding(cfg.n_commands, cfg.d_model)

        args_dim = cfg.args_dim + 1
        self.arg_embed = nn.Embedding(args_dim, 64, padding_idx=0)
        self.embed_fcn = nn.Linear(64 * cfg.n_args, cfg.d_model)

        # use_group: additional embedding for each sketch-extrusion pair
        self.use_group = use_group
        if use_group:
            if group_len is None:
                group_len = cfg.max_num_groups
            self.group_embed = nn.Embedding(group_len + 2, cfg.d_model)

        self.pos_encoding = PositionalEncodingLUT(cfg.d_model, max_len=seq_len+2)

    def forward(self, commands, args, groups=None):
        S, N = commands.shape

        src = self.command_embed(commands.long()) + \
              self.embed_fcn(self.arg_embed((args + 1).long()).view(S, N, -1))  # shift due to -1 PAD_VAL

        if self.use_group:
            src = src + self.group_embed(groups.long())

        src = self.pos_encoding(src)

        return src

In [193]:
class Decoder(nn.Module):
    def __init__(self, cfg):
        super(Decoder, self).__init__()

        self.embedding = ConstEmbedding(cfg, cfg.max_total_len)

        decoder_layer = TransformerDecoderLayerGlobalImproved(cfg.d_model, cfg.dim_z, cfg.n_heads, cfg.dim_feedforward, cfg.dropout)
        decoder_norm = LayerNorm(cfg.d_model)
        self.decoder = TransformerDecoder(decoder_layer, cfg.n_layers_decode, decoder_norm)

        args_dim = cfg.args_dim + 1
        self.fcn = FCN(cfg.d_model, cfg.n_commands, cfg.n_args, args_dim)

    def forward(self, z):
        src = self.embedding(z)
        out = self.decoder(src, z, tgt_mask=None, tgt_key_padding_mask=None)

        command_logits, args_logits = self.fcn(out)

        out_logits = (command_logits, args_logits)
        return out_logits

In [194]:
class Encoder(nn.Module):
    def __init__(self, cfg):
        super().__init__()

        seq_len = cfg.max_total_len
        self.use_group = cfg.use_group_emb
        self.embedding = CADEmbedding(cfg, seq_len, use_group=self.use_group)

        encoder_layer = TransformerEncoderLayerImproved(cfg.d_model, cfg.n_heads, cfg.dim_feedforward, cfg.dropout)
        encoder_norm = LayerNorm(cfg.d_model)
        self.encoder = TransformerEncoder(encoder_layer, cfg.n_layers, encoder_norm)

    def forward(self, commands, args):
        padding_mask, key_padding_mask = _get_padding_mask(commands, seq_dim=0), _get_key_padding_mask(commands, seq_dim=0)
        group_mask = _get_group_mask(commands, seq_dim=0) if self.use_group else None

        src = self.embedding(commands, args, group_mask)

        memory = self.encoder(src, mask=None, src_key_padding_mask=key_padding_mask)

        z = (memory * padding_mask).sum(dim=0, keepdim=True) / padding_mask.sum(dim=0, keepdim=True) # (1, N, dim_z)
        return z

In [195]:
from model.layers.transformer import *
from model.layers.improved_transformer import *
from model.layers.positional_encoding import *
from model.model_utils import _make_seq_first, _make_batch_first, \
    _get_padding_mask, _get_key_padding_mask, _get_group_mask
class CADTransformer(nn.Module):
    def __init__(self, cfg):
        super(CADTransformer, self).__init__()

        self.args_dim = cfg.args_dim + 1

        self.encoder = Encoder(cfg)

        self.bottleneck = Bottleneck(cfg)

        self.decoder = Decoder(cfg)

    def forward(self, commands_enc, args_enc,
                z=None, return_tgt=True, encode_mode=False):
        commands_enc_, args_enc_ = _make_seq_first(commands_enc, args_enc)  # Possibly None, None

        if z is None:
            z = self.encoder(commands_enc_, args_enc_)
            z = self.bottleneck(z)
        else:
            z = _make_seq_first(z)

        if encode_mode: return _make_batch_first(z)

        out_logits = self.decoder(z)
        out_logits = _make_batch_first(*out_logits)

        res = {
            "command_logits": out_logits[0],
            "args_logits": out_logits[1]
        }

        if return_tgt:
            res["tgt_commands"] = commands_enc
            res["tgt_args"] = args_enc

        return res

## BaseTrainer

In [196]:
import os
import torch
import torch.optim as optim
import torch.nn as nn
from abc import abstractmethod
from tensorboardX import SummaryWriter

class BaseTrainer(object):
    """Base trainer that provides common training behavior.
        All customized trainer should be subclass of this class.
    """
    def __init__(self, cfg):
        self.cfg = cfg

        self.log_dir = cfg.log_dir
        self.model_dir = cfg.model_dir
        self.clock = TrainClock()
        self.batch_size = cfg.batch_size

        # build network
        self.build_net(cfg)

        # set loss function
        self.set_loss_function()

        # set optimizer
        self.set_optimizer(cfg)

        # set tensorboard writer
        self.train_tb = SummaryWriter(os.path.join(self.log_dir, 'train.events'))
        self.val_tb = SummaryWriter(os.path.join(self.log_dir, 'val.events'))

    @abstractmethod
    def build_net(self, cfg):
        raise NotImplementedError

    def set_loss_function(self):
        """set loss function used in training"""
        pass

    def set_optimizer(self, cfg):
        """set optimizer and lr scheduler used in training"""
        self.optimizer = optim.Adam(self.net.parameters(), cfg.lr)
        self.scheduler = optim.lr_scheduler.StepLR(self.optimizer, cfg.lr_step_size)

    def save_ckpt(self, name=None):
        """save checkpoint during training for future restore"""
        if name is None:
            save_path = os.path.join(self.model_dir, "ckpt_epoch{}.pth".format(self.clock.epoch))
            print("Saving checkpoint epoch {}...".format(self.clock.epoch))
        else:
            save_path = os.path.join(self.model_dir, "{}.pth".format(name))

        if isinstance(self.net, nn.DataParallel):
            model_state_dict = self.net.module.cpu().state_dict()
        else:
            model_state_dict = self.net.cpu().state_dict()

        torch.save({
            'clock': self.clock.make_checkpoint(),
            'model_state_dict': model_state_dict,
            'optimizer_state_dict': self.optimizer.state_dict(),
            'scheduler_state_dict': self.scheduler.state_dict(),
        }, save_path)

        self.net#.cuda()

    def load_ckpt(self, name=None):
        """load checkpoint from saved checkpoint"""
        name = name if name == 'latest' else "ckpt_epoch{}".format(name)
        load_path = os.path.join(self.model_dir, "{}.pth".format(name))
        if not os.path.exists(load_path):
            raise ValueError("Checkpoint {} not exists.".format(load_path))

        checkpoint = torch.load(load_path, map_location=torch.device('cpu'), weights_only=True)
        print("Loading checkpoint from {} ...".format(load_path))
        if isinstance(self.net, nn.DataParallel):
            self.net.module.load_state_dict(checkpoint['model_state_dict'])
        else:
            self.net.load_state_dict(checkpoint['model_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        self.clock.restore_checkpoint(checkpoint['clock'])

    @abstractmethod
    def forward(self, data):
        """forward logic for your network"""
        """should return network outputs, losses(dict)"""
        raise NotImplementedError

    def update_network(self, loss_dict):
        """update network by back propagation"""
        loss = sum(loss_dict.values())
        self.optimizer.zero_grad()
        loss.backward()
        if self.cfg.grad_clip is not None:
            nn.utils.clip_grad_norm_(self.net.parameters(), self.cfg.grad_clip)
        self.optimizer.step()

    def update_learning_rate(self):
        """record and update learning rate"""
        self.train_tb.add_scalar('learning_rate', self.optimizer.param_groups[-1]['lr'], self.clock.epoch)
        self.scheduler.step()

    def record_losses(self, loss_dict, mode='train'):
        """record loss to tensorboard"""
        losses_values = {k: v.item() for k, v in loss_dict.items()}

        tb = self.train_tb if mode == 'train' else self.val_tb
        for k, v in losses_values.items():
            tb.add_scalar(k, v, self.clock.step)

    def train_func(self, data):
        """one step of training"""
        self.net.train()

        outputs, losses = self.forward(data)

        self.update_network(losses)
        if self.clock.step % 10 == 0:
            self.record_losses(losses, 'train')

        return outputs, losses

    def val_func(self, data):
        """one step of validation"""
        self.net.eval()

        with torch.no_grad():
            outputs, losses = self.forward(data)

        self.record_losses(losses, 'validation')

        return outputs, losses

    def visualize_batch(self, data, tb, **kwargs):
        """write visualization results to tensorboard writer"""
        raise NotImplementedError

class TrainClock(object):
    """ Clock object to track epoch and step during training
    """
    def __init__(self):
        self.epoch = 1
        self.minibatch = 0
        self.step = 0

    def tick(self):
        self.minibatch += 1
        self.step += 1

    def tock(self):
        self.epoch += 1
        self.minibatch = 0

    def make_checkpoint(self):
        return {
            'epoch': self.epoch,
            'minibatch': self.minibatch,
            'step': self.step
        }

    def restore_checkpoint(self, clock_dict):
        self.epoch = clock_dict['epoch']
        self.minibatch = clock_dict['minibatch']
        self.step = clock_dict['step']


## TrainerAE

In [197]:
import torch
import torch.optim as optim
from tqdm import tqdm
from trainer.loss import CADLoss
from trainer.scheduler import GradualWarmupScheduler


class TrainerAE(BaseTrainer):
    def build_net(self, cfg):
        self.net = CADTransformer(cfg)#.cuda()

    def set_optimizer(self, cfg):
        """set optimizer and lr scheduler used in training"""
        self.optimizer = optim.Adam(self.net.parameters(), cfg.lr)
        self.scheduler = GradualWarmupScheduler(self.optimizer, 1.0, cfg.warmup_step)

    def set_loss_function(self):
        self.loss_func = CADLoss(self.cfg)#.cuda()

    def forward(self, data):
        commands = data['command']#.cuda() # (N, S)
        args = data['args']#.cuda()  # (N, S, N_ARGS)

        outputs = self.net(commands, args)
        loss_dict = self.loss_func(outputs)

        return outputs, loss_dict

    def encode(self, data, is_batch=False):
        """encode into latent vectors"""
        commands = data['command']#.cuda()
        args = data['args']#.cuda()
        if not is_batch:
            commands = commands.unsqueeze(0)
            args = args.unsqueeze(0)
        z = self.net(commands, args, encode_mode=True)
        return z

    def decode(self, z):
        """decode given latent vectors"""
        outputs = self.net(None, None, z=z, return_tgt=False)
        return outputs

    def logits2vec(self, outputs, refill_pad=True, to_numpy=True):
        """network outputs (logits) to final CAD vector"""
        out_command = torch.argmax(torch.softmax(outputs['command_logits'], dim=-1), dim=-1)  # (N, S)
        out_args = torch.argmax(torch.softmax(outputs['args_logits'], dim=-1), dim=-1) - 1  # (N, S, N_ARGS)
        if refill_pad: # fill all unused element to -1
            mask = ~torch.tensor(CMD_ARGS_MASK).bool()[out_command.long()] #.cuda() infront of [out_command.long()]
            out_args[mask] = -1

        out_cad_vec = torch.cat([out_command.unsqueeze(-1), out_args], dim=-1)
        if to_numpy:
            out_cad_vec = out_cad_vec.detach().cpu().numpy()
        return out_cad_vec

    def evaluate(self, test_loader):
        """evaluatinon during training"""
        self.net.eval()
        pbar = tqdm(test_loader)
        pbar.set_description("EVALUATE[{}]".format(self.clock.epoch))

        all_ext_args_comp = []
        all_line_args_comp = []
        all_arc_args_comp = []
        all_circle_args_comp = []

        for i, data in enumerate(pbar):
            with torch.no_grad():
                commands = data['command']#.cuda()
                args = data['args']#.cuda()
                outputs = self.net(commands, args)
                out_args = torch.argmax(torch.softmax(outputs['args_logits'], dim=-1), dim=-1) - 1
                out_args = out_args.long().detach().cpu().numpy()  # (N, S, n_args)

            gt_commands = commands.squeeze(1).long().detach().cpu().numpy() # (N, S)
            gt_args = args.squeeze(1).long().detach().cpu().numpy() # (N, S, n_args)

            ext_pos = np.where(gt_commands == EXT_IDX)
            line_pos = np.where(gt_commands == LINE_IDX)
            arc_pos = np.where(gt_commands == ARC_IDX)
            circle_pos = np.where(gt_commands == CIRCLE_IDX)

            args_comp = (gt_args == out_args).astype(np.int)
            all_ext_args_comp.append(args_comp[ext_pos][:, -N_ARGS_EXT:])
            all_line_args_comp.append(args_comp[line_pos][:, :2])
            all_arc_args_comp.append(args_comp[arc_pos][:, :4])
            all_circle_args_comp.append(args_comp[circle_pos][:, [0, 1, 4]])

        all_ext_args_comp = np.concatenate(all_ext_args_comp, axis=0)
        sket_plane_acc = np.mean(all_ext_args_comp[:, :N_ARGS_PLANE])
        sket_trans_acc = np.mean(all_ext_args_comp[:, N_ARGS_PLANE:N_ARGS_PLANE+N_ARGS_TRANS])
        extent_one_acc = np.mean(all_ext_args_comp[:, -N_ARGS_EXT_PARAM])
        line_acc = np.mean(np.concatenate(all_line_args_comp, axis=0))
        arc_acc = np.mean(np.concatenate(all_arc_args_comp, axis=0))
        circle_acc = np.mean(np.concatenate(all_circle_args_comp, axis=0))

        self.val_tb.add_scalars("args_acc",
                                {"line": line_acc, "arc": arc_acc, "circle": circle_acc,
                                 "plane": sket_plane_acc, "trans": sket_trans_acc, "extent": extent_one_acc},
                                global_step=self.clock.epoch)


## Datalaoder

In [198]:
from torch.utils.data import Dataset, DataLoader
import torch
import os
import json
import h5py
import random

def get_dataloader(phase, config, shuffle=None):
    is_shuffle = phase == 'train' if shuffle is None else shuffle
    dataset = CADDataset(phase, config)
    dataloader = DataLoader(dataset, batch_size=config.batch_size, shuffle=is_shuffle, num_workers=config.num_workers,
                            worker_init_fn=np.random.seed())
    return dataloader


class CADDataset(Dataset):
    def __init__(self, phase, config):
        super(CADDataset, self).__init__()
        self.raw_data = os.path.join(config.data_root, "cad_vec") # h5 data root
        self.phase = phase
        self.aug = config.augment
        self.path = os.path.join(config.data_root, "train_val_test_split.json")
        with open(self.path, "r") as fp:
            self.all_data = json.load(fp)[phase]
        self.max_n_loops = config.max_n_loops          # Number of paths (N_P)
        self.max_n_curves = config.max_n_curves            # Number of commands (N_C)
        self.max_total_len = config.max_total_len
        self.size = 256

    def get_data_by_id(self, data_id):
        idx = self.all_data.index(data_id)
        return self.__getitem__(idx)

    def __getitem__(self, index):
        data_id = self.all_data[index]
        h5_path = os.path.join(self.raw_data, data_id + ".h5")
        with h5py.File(h5_path, "r") as fp:
            cad_vec = fp["vec"][:] # (len, 1 + N_ARGS)

        if self.aug and self.phase == "train":
            command1 = cad_vec[:, 0]
            ext_indices1 = np.where(command1 == EXT_IDX)[0]
            # if len(ext_indices1) > 1 and random.randint(0, 1) == 1:
            if len(ext_indices1) > 1 and random.uniform(0, 1) > 0.5:
                ext_vec1 = np.split(cad_vec, ext_indices1 + 1, axis=0)[:-1]
        
                data_id2 = self.all_data[random.randint(0, len(self.all_data) - 1)]
                h5_path2 = os.path.join(self.raw_data, data_id2 + ".h5")
                with h5py.File(h5_path2, "r") as fp:
                    cad_vec2 = fp["vec"][:]
                command2 = cad_vec2[:, 0]
                ext_indices2 = np.where(command2 == EXT_IDX)[0]
                ext_vec2 = np.split(cad_vec2, ext_indices2 + 1, axis=0)[:-1]
        
                n_replace = random.randint(1, min(len(ext_vec1) - 1, len(ext_vec2)))
                old_idx = sorted(random.sample(list(range(len(ext_vec1))), n_replace))
                new_idx = sorted(random.sample(list(range(len(ext_vec2))), n_replace))
                for i in range(len(old_idx)):
                    ext_vec1[old_idx[i]] = ext_vec2[new_idx[i]]
        
                sum_len = 0
                new_vec = []
                for i in range(len(ext_vec1)):
                    sum_len += len(ext_vec1[i])
                    if sum_len > self.max_total_len:
                        break
                    new_vec.append(ext_vec1[i])
                cad_vec = np.concatenate(new_vec, axis=0)

        pad_len = self.max_total_len - cad_vec.shape[0]
        cad_vec = np.concatenate([cad_vec, EOS_VEC[np.newaxis].repeat(pad_len, axis=0)], axis=0)

        command = cad_vec[:, 0]
        args = cad_vec[:, 1:]
        command = torch.tensor(command, dtype=torch.long)
        args = torch.tensor(args, dtype=torch.long)
        return {"command": command, "args": args, "id": data_id}

    def __len__(self):
        return len(self.all_data)


## Main

In [199]:
from tqdm import tqdm
from utils import ensure_dir
import torch
import numpy as np
import os
import h5py
from cadlib.macro import EOS_IDX

cfg = ConfigAE('test')

#### reconstruct(cfg) method
tr_agent = TrainerAE(cfg)
tr_agent.load_ckpt(cfg.ckpt)
tr_agent.net.eval()
test_loader = get_dataloader('test', cfg)
print("Total number of batches (size: {}) data:{}".format(cfg.batch_size, len(test_loader)))
if cfg.outputs is None:
    cfg.outputs = "{}/results/test_{}".format(cfg.exp_dir, cfg.ckpt)
ensure_dir(cfg.outputs)
print(len(test_loader))
for i, data in enumerate(test_loader):
    print(i)
    commands = data['command']
    args = data['args']
    print("Commands shape: ", commands.shape)
    print("Args shape: ", args.shape)
    print(torch.cat([commands.unsqueeze(-1), args], dim=-1).shape)
    print(torch.cat([commands.unsqueeze(-1), args], dim=-1).squeeze(1).shape)
    gt_vec = torch.cat([commands.unsqueeze(-1), args], dim=-1).squeeze(1).detach().cpu().numpy()
    commands_ = gt_vec[:, :, 0]
    print(commands_.shape)
    with torch.no_grad():
        outputs, _ = tr_agent.forward(data)
        batch_out_vec = tr_agent.logits2vec(outputs)

    
    

    
  #  print(gt_vec.shape)
    break

----Experiment Configuration-----
proj_dir             ../DeepCAD/proj_log
data_root            ../DeepCAD/data
exp_name             pretrained
gpu_ids              0
batch_size           512
num_workers          0
nr_epochs            1000
lr                   0.001
grad_clip            1.0
warmup_step          2000
cont                 False
ckpt                 1000
vis                  False
save_frequency       500
val_frequency        10
vis_frequency        2000
augment              False
mode                 rec
outputs              None
z_path               None
Loading checkpoint from ../DeepCAD/proj_log/pretrained/model/ckpt_epoch1000.pth ...
Total number of batches (size: 512) data:16
16
0
Commands shape:  torch.Size([512, 60])
Args shape:  torch.Size([512, 60, 16])
torch.Size([512, 60, 17])
torch.Size([512, 60, 17])
(512, 60)


In [200]:
os.path.exists('../DeepCAD/proj_log/pretrained/model/ckpt_epoch1000.pth')

True

In [201]:
print(batch_out_vec.shape)

(512, 60, 17)


In [202]:
outputs.keys()

dict_keys(['command_logits', 'args_logits', 'tgt_commands', 'tgt_args'])

Verstanden:
- ungefähr die struktur von dem Ding
- woher die Daten kommen

Next: Für ein Beispiel erklären wie es funktioniert, dafür gibt es diese _make_seq_first funktion

In [203]:

command_logits = outputs['command_logits']
args_logits = outputs['args_logits']
tgt_commands = outputs['tgt_commands']
tgt_args = outputs['tgt_args']

In [204]:
command_logits.shape, args_logits.shape, tgt_commands.shape, tgt_args.shape

(torch.Size([512, 60, 6]),
 torch.Size([512, 60, 16, 257]),
 torch.Size([512, 60]),
 torch.Size([512, 60, 16]))

In [205]:
batch = 58
command = 13

In [206]:
tgt_commands[batch]

tensor([4, 0, 0, 0, 0, 5, 4, 2, 5, 4, 0, 0, 0, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [207]:
tgt_args[batch,command]

tensor([ -1,  -1,  -1,  -1,  -1, 192,  64, 192,  86, 128, 227,  90, 210, 128,
          2,   1])

In [208]:
args_logits[batch, command, 14].argmax()

tensor(3)

In [209]:
batch_out_vec[batch, command]

array([  5,  -1,  -1,  -1,  -1,  -1, 192,  64, 192,  86, 128, 201,  90,
       210, 155,   2,   2])

In [210]:
for i, batch in enumerate(batch_out_vec):
    for j, command in enumerate(batch):
        if command[-1] == 2:
            print(i, j)
            break

58 13
113 17
120 11
136 7
194 2
245 5
347 20
361 4
390 5
391 12
467 4


In [211]:
def reconstruct(cfg):
    # create network and training agent
    tr_agent = TrainerAE(cfg)

    # load from checkpoint if provided
    tr_agent.load_ckpt(cfg.ckpt)
    tr_agent.net.eval()

    # create dataloader
    test_loader = get_dataloader('test', cfg)
    print("Total number of test data:", len(test_loader))

    if cfg.outputs is None:
        cfg.outputs = "{}/results/test_{}".format(cfg.exp_dir, cfg.ckpt)
    ensure_dir(cfg.outputs)

    # evaluate
    pbar = tqdm(test_loader)
    for i, data in enumerate(pbar):
        batch_size = data['command'].shape[0]
        commands = data['command']
        args = data['args']
        gt_vec = torch.cat([commands.unsqueeze(-1), args], dim=-1).squeeze(1).detach().cpu().numpy()
        commands_ = gt_vec[:, :, 0]
        with torch.no_grad():
            outputs, _ = tr_agent.forward(data)
            batch_out_vec = tr_agent.logits2vec(outputs)

        for j in range(batch_size):
            out_vec = batch_out_vec[j]
            seq_len = commands_[j].tolist().index(EOS_IDX)

            data_id = data["id"][j].split('/')[-1]

            save_path = os.path.join(cfg.outputs, '{}_vec.h5'.format(data_id))
            with h5py.File(save_path, 'w') as fp:
                fp.create_dataset('out_vec', data=out_vec[:seq_len], dtype=int)
                fp.create_dataset('gt_vec', data=gt_vec[j][:seq_len], dtype=int)

In [212]:
def _make_seq_first(*args):
    # N, S, ... -> S, N, ...
    if len(args) == 1:
        arg, = args
        return arg.permute(1, 0, *range(2, arg.dim())) if arg is not None else None
    return (*(arg.permute(1, 0, *range(2, arg.dim())) if arg is not None else None for arg in args),)

# Minimum Working Example

First let's generate a data sampel with the batch size of 1 and set up the configurations for testing. The ```ConfigAE``` method basically sets all parameters of the model and has been modified according to this notebooks's needs. The method can be seen in the beginning of the notebook, but it does not add much information for understanding how the model works, which is why it is ommited now.

In [324]:
# Configure models
cfg = ConfigAE('test')

# Get a single sample
test_loader = get_dataloader('test', cfg)
batch_sample = 0
for i, data in enumerate(test_loader):
    commands = data['command']
    args = data['args']
    commands = commands[batch_sample].unsqueeze(0)
    args = args[batch_sample].unsqueeze(0)
    print("\nCommands shape: ", commands.shape)
    print("Args shape: ", args.shape)
    break

----Experiment Configuration-----
proj_dir             ../DeepCAD/proj_log
data_root            ../DeepCAD/data
exp_name             pretrained
gpu_ids              0
batch_size           512
num_workers          0
nr_epochs            1000
lr                   0.001
grad_clip            1.0
warmup_step          2000
cont                 False
ckpt                 1000
vis                  False
save_frequency       500
val_frequency        10
vis_frequency        2000
augment              False
mode                 rec
outputs              None
z_path               None

Commands shape:  torch.Size([1, 60])
Args shape:  torch.Size([1, 60, 16])


In [325]:
print(commands)

tensor([[4, 0, 0, 0, 0, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


If we look into the first command sequence of the test set, we can see that this sequence describes: SOL - Line x 4 - Extrusion, some kind of prism.

## CADTransformer
The input data is first fed to the CADTransformer which consists of a **Encoder**, **Bottleneck** and **Decoder**. 
The CADTransformer first permutes the order of dimensions from ```batch```x```commands```x```args``` to: ```commands```x```batch```x```args```

In [326]:
commands_enc, args_enc = _make_seq_first(commands, args)  # Possibly None, None
print(commands_enc.shape)
print(args_enc.shape)

torch.Size([60, 1])
torch.Size([60, 1, 16])


The forward method of the CADTransformer has different modes of operation: Either a latent vector **z** is given or not. If it is not given, which is the case we are looking at now, the commands and args are fed into the Encoder. The other case will be interesting as soon as we train a point cloud encoder for the same latent space **z**.

### Encoder

- ```seq_len``` is the maximum sequence length of commands, which is set to 60 according to the paper
- ```use_group``` is a boolean for to enable group learning

The Encoder first creates a ```padding_mask```, ```key_padding_mask``` and a ```group_mask```. The scripts are located in ```model_utils.py```.
- ```padding_mask``` creates a boolean int tensor which marks every command which is valid (in our case 6 commands are valid and the remaining 54 are not.
- ```key_padding_mask``` creates a boolean tensor marking all valid (i.e. all commands except EOS) commands with False. Later all comands marked with True (i.e. non-valid commands) are filled in with ```-inf``` during multi-head-attention.
- ```group_mask``` creates a tensor of length 60 (seq_length), where all commands belonging to an extrusion (cmd_idx: 5) sequence get the same number, i.e. [4, 2, 5, 4, 2, 5, 4, 0] --> [0, 0, 1, 1, 1, 2, 2, 2]

In [327]:
# Encoder

## Definition
seq_len = cfg.max_total_len
print("Sequence length:", seq_len)
use_group = cfg.use_group_emb
print("Use group:", use_group)

## Forward
padding_mask, key_padding_mask = _get_padding_mask(commands_enc, seq_dim=0), _get_key_padding_mask(commands_enc, seq_dim=0)
group_mask = _get_group_mask(commands_enc, seq_dim=0) if use_group else None

Sequence length: 60
Use group: True


After creating the masks, the Encoder embedds the command sequene using ```CADEmbedding```

#### CADEmbedding

The CADEmbedding module consists of lookup tables for the commands and args, as well as linear layers for transformation.
- ```command_embed``` (6, 256) -> Lookup table for each of the 6 commands with embedding of dim 256
- ```args_dim``` Adds another dimension to the parameters if the parameter is unused
- ```arg_embed``` (257, 64) -> Every parameter is quantized in $2^8$ bits and each of these $256$ bits gets an embedding of dim $64$ through a lookup table. The 257'th dimension is there if a parameter is not used in the command. All args with value 0 are not contributing to the gradient.
- ```embed_fcn``` (64 * 16 = 1024, 256) -> linear layer to project the flattened parameter embeddings to the model dimension
- ```group_embed``` (32,256) -> Lookup table for groups (max. 30 groups), 2 extra for beginning and end. There is no mention of that in the paper
- ```pos_encoding``` (64+2=66, 256) -> Learnable positional encoding for each of the 64 position, 2 extra for SOS and EOS

In the forward method the command and parameter embedding are added, as well as the positional encoding and the group embedding.

In [328]:
# Embedding

## Defintion
command_embed = nn.Embedding(cfg.n_commands, cfg.d_model) 
args_dim = cfg.args_dim + 1 # 257 
arg_embed = nn.Embedding(args_dim, 64, padding_idx=0) 
embed_fcn = nn.Linear(64 * cfg.n_args, cfg.d_model) # 64 * 16 = 1024, 256 -> Projects the flattened args to dim 256
if use_group:
    group_len = cfg.max_num_groups # 30
    group_embed = nn.Embedding(group_len + 2, cfg.d_model) # whatever this group thing is, but it projects them from dim 32 to dim 256
pos_encoding = PositionalEncodingLUT(cfg.d_model, max_len=seq_len+2) # -> Adds a learnable positional encoding (initialized with kaiming)

## Forward
S, N = commands_enc.shape
src = command_embed(commands_enc.long())  
src += embed_fcn(arg_embed((args_enc + 1).long()).view(S, N, -1)) # shift due to -1 PAD_VAL
if use_group:
    src = src + group_embed(group_mask.long())
src = pos_encoding(src)
print(src.shape)

torch.Size([60, 1, 256])


### Encoder (Continuation)

After the Embedding layer was called in the Encoder, the Encoder calls the encoder layer with this line on the embeddings: 

```memory = self.encoder(src, mask=None, src_key_padding_mask=key_padding_mask)```

The Encoder consists of multiple TransformerEncoderLayer's which are concatenetead in a list using ```_get_clones()```. Each TransformerEncoderLayer[Improved] is then called sequentially on the ```src``` values from the embedding. TransformerEncoderLayer[Improved] is basically a Transformer encoder with normalization --> self attention --> dropout --> residual connection --> normalization --> linear layer --> dropout --> residual connection. It would be too much and unnecessary to write all of this down, which is why the class is imported. **Important** to note is that the keys queries and values are calculated from the embeddings as usual. 

The embeddings of the commands are processed by ```self.n_layers = 4``` encoder layers and the attention mechanism will assign the attention. A final single layer of Layer normalization is applied afterwards (LN is already applied in the encoder).

To calculate the latent vector **z**, first the padding mask is applied to memory which leaves only memory entries at valid commands (all comands except EOS). Then the embeddings of all valid commands are averaged, i.e. they are added along the command dimension and divided by the number of commands (global averaging).

In [336]:
# Encoder 2
def _get_clones(module, N):
    return ModuleList([copy.deepcopy(module) for i in range(N)])
    
encoder_layer = TransformerEncoderLayerImproved(cfg.d_model, cfg.n_heads, cfg.dim_feedforward, cfg.dropout)
layers = _get_clones(encoder_layer, cfg.n_layers)
encoder_norm = LayerNorm(cfg.d_model)

output = src
for mod in layers: # Encoder layers
    output = mod(output, memory2=None, src_mask=None, src_key_padding_mask=key_padding_mask)

if encoder_norm is not None:
    memory = encoder_norm(output)
print(memory.shape)

z = (memory * padding_mask).sum(dim = 0, keepdim = True)/padding_mask.sum(dim = 0, keepdim = True)
print(z.shape)


torch.Size([60, 1, 256])
torch.Size([1, 1, 256])


## Bottleneck

After the Encoder encoded the command and parameter sequence, the latent vector **z** is passed through the bottleneck. The bottleneck consists of a simple linear layer with a tanh non-linearity.

In [338]:
bottleneck = nn.Sequential(nn.Linear(cfg.d_model, cfg.dim_z), nn.Tanh())
z = bottleneck(z)
print(z.shape)

torch.Size([1, 1, 256])


## Decoder

After the bottleneck, the Decoder will try to decode the latent vector back to the original command sequence. The latent vector is first embedded and then decoded by the Decoder. Finally the decoded latent vector is passed through a Fully Connected Layer which results in the command and parameter logits. We will go step by step and start with the ```ConstEmbedding``` which is used for embedding the latent vector.

### Embedding
The embedding consist only of a positional encoding using a learnable lookup table (LUT) which will be shown now.

In [369]:
N = z.size(1)

#### Learnable Positional Encoding

For the positional encoding, the dropout layer, a tensor consisiting of all the 60 (seq_length) positions (0 to 59) and an embedding/lookup table is initialized. Kaiming weight initalization is applied to the lookup table. In the forward method, the following happens: 
- ```z_new``` is initialized with the ```new_zeros()``` method, which creates a zero tensor of the same shape and the same device as the argument tensor --> This is basically to prevent compatibility issues
- ```pos``` checks the valid positions of the tensor, i.e. if the tensors sequence lenght is 60, only 60 positions are valid

The positional embedding is then added on top of the newly created zero tensor and the positional encoding is obtained. The positional encoding will the be passed alongside the latent vector **z** to the decoder.

In [384]:
## Definition
dropout = nn.Dropout(p = 0.1)
position = torch.arange(0, seq_len, dtype = torch.long).unsqueeze(1)
pos_embed = nn.Embedding(60, 256)
nn.init.kaiming_normal_(pos_embed.weight, mode="fan_in")

## Forward
z_new = z.new_zeros(60, 1, 256)
pos = position[:z_new.size(0)]
z_new = z_new + pos_embed(pos)
src = dropout(z_new)

## Decoder (Continuation)

After the positional encoding was obtained, it is passed alongside the latent vector **z** to the decoder layers. The decoder first copies the decoder layers. The input to a decoder layer is the positional encoding ```src``` and the latent vector **z**. A decoder layer is basically the decoder layer from the Attention is all you need paper. It takes the positional encoding of the input sequence as input to the first decoder block, i.e. the positional encoding is normalized, self attention is applied and a dropout layer. The original input is then added in a residual connection. In the second decoder block cross-attention is applied, i.e. the self attention values from the positional encodings are normalized and used as queries and the latent vector **z** is used as key and value values. This basically means, that the decoder looks into the keys of the encoder by using the queries to know how to further decode the sequence. The answer to this comparison (dot product similarity) is reflected in the attention values. Again a residual connection with droput combines the outputs of the frist and second decoder block. A final normlization, linear and dropout layer is used to generate the outputs. After this a final normalization layer is applied.

In [385]:
n_layers_dedecoder_layer = TransformerDecoderLayerGlobalImproved(cfg.d_model, cfg.dim_z, cfg.n_heads, cfg.dim_feedforward, cfg.dropout)
layers = _get_clones(decoder_layer, 4)
decoder_norm = LayerNorm(cfg.d_model)

for mod in layers:
    output = mod(src, # positional embedding
                 z) # latent vector z
if decoder_norm is not None:
    output = decoder_norm(output)


### Fully Connected Layer

After the Decoder used the attention mechanism to refine the outputs of the encoder and combined them with the sequence, a Fully Connected Layer is employed to get the final command and parameter logits. The FCN consists of two simple linear layers, one for the commands and one for the parameters.

In [390]:
## Definition
command_fcn = nn.Linear(256, 6)
args_fcn = nn.Linear(256, 16 * 256) #n_args * args_dim  rfub fvub

## Forward
command_logits = command_fcn(output)  # Shape [S, N, n_commands]
args_logits = args_fcn(output) # Shape [S, N, n_args * args_dim]
args_logits = args_logits.reshape(S, N, 16, 256)


In [394]:
command_logits.shape, args_logits.shape

(torch.Size([60, 1, 6]), torch.Size([60, 1, 16, 256]))

This concludes the forward method of the entire **CADTransformer**. The last step is to convert the logits to a CAD vector using the function ```logits2vec```.

## logits2vec

First softmax is applied to both the commands and parameters. Then the maximum softmax probability argument is chosen. Then a mask is applied to only choose the parameters that are necessary for the command. Finally the commands and args are concatenated to form the CAD sequence.

In [411]:
out_command = torch.argmax(torch.softmax(command_logits, dim=-1), dim=-1)  # (N, S)
out_args = torch.argmax(torch.softmax(args_logits, dim=-1), dim=-1) - 1  # (N, S, N_ARGS)
out_command.shape
# fill all unused element to -1
mask = ~torch.tensor(CMD_ARGS_MASK).bool()[out_command.long()] #.cuda() infront of [out_command.long()]
out_args[mask] = -1
out_cad_vec = torch.cat([out_command.unsqueeze(-1), out_args], dim=-1)
out_cad_vec = out_cad_vec.detach().cpu().numpy()
out_cad_vec.shape

(60, 1, 17)

In [415]:
out_cad_vec[0]

array([[  0, 233, 212,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
         -1,  -1,  -1,  -1]])

Now of course in this MWE the model is not trained so the results will not make sense. The next step is to scrutinize the quantization of parameters.

# Conversion to .step

Next, I want to scrutinize how the transformation of a sequence into CAD formats like ```.step``` works. In the file ```export2step``` first a ```CADSequence``` class object is created and the the function ```create_CAD()``` is invoked. The following two paths are for the first test sample 0025/00250456 the input and reconstructed vector sequence and the point cloud. 

In [653]:
vec_seq_ex = "../DeepCAD/data/cad_vec/0025/00000915_vec.h5"#00250456.h5
vec_seq_rec_ex = "../DeepCAD/proj_log/pretrained/results/test_1000/00000915_vec.h5"
pc_ex = "../DeepCAD/data/pc_cad/0025/00250456.ply"

Looking at the point cloud in CloudCompare, it definetly is a cube. Comparing with the input vector sequence, it is easier to see, that is also sketches a quadratic plane and extrudes it. Fortunately the reconstructed CAD sequence stores the input CAD sequence, so we can observe both in one file.

In [654]:
file_name = vec_seq_rec_ex
with h5py.File(file_name, 'r') as f:
    for key in f.keys():
        print(f"key - {key}: {f[key]}")
        data = f[key][()]
        print(data)

key - gt_vec: <HDF5 dataset "gt_vec": shape (6, 17), type "<i8">
[[  4  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 203  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 203  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  5  -1  -1  -1  -1  -1 192  64 192  32 128 157  68 165 128   0   0]]
key - out_vec: <HDF5 dataset "out_vec": shape (6, 17), type "<i8">
[[  4  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 223 203  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 203  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  5  -1  -1  -1  -1  -1 192  64 192  32 128 157  68 165 128   0   0]]


In [585]:
with h5py.File(vec_seq_rec_ex, 'r') as fp:
    out_vec = fp["out_vec"][:].astype(np.float64)

In order to turn the CAD sequence to a step file, first the CAD sequence is converted into a numpy tensor. Then a method ```vec2CADsolid``` is called on the numpy array. The method uses a ```CADSequence.from_vector()``` static (i.e. there does not need to exist a instance of ```CADSequence```) class method on the numpy array.  

## CADSequence.from_vector()

Firs the commands are extracted. Then the indices of all extrusion commands are extracted. A for loop iterates through all extrusions and calls the ```Extrude.from_vector()``` static class method.

In [586]:
is_numerical = True
commands = out_vec[:, 0]
print(commands.shape)
ext_indices = [-1] + np.where(commands == EXT_IDX)[0].tolist()
ext_seq = []
for i in range(len(ext_indices) - 1):
    start, end = ext_indices[i], ext_indices[i + 1]
    print(start, end)

(6,)
-1 5


In [587]:
print(out_vec.shape)
out_vec = out_vec[start+1:end+1]
print(out_vec.shape)

(6, 17)
(6, 17)


## Extrude.from_vector()

The method first checks if the sequence starts with SOL and ends with EXT command. Then it creates a profile vector ```profile_vec```, in which the extrusion command is switched with the EOS vector (EOS index at 0, rest padding). A class ```Profile``` is created, which is described below. In ```ext_vec``` the parameters of the extrusion are extracted from the parameters of the extrusion (Index: 5) command. ```sket_size```extracts s which is the bounding box skaling faktor.  ```sket_pos```extracts 3 plane translation parameters p_x, p_y, p_z which are the orgin of the previous plane. ```sket_pos``` and the 3 plane orientation parameters theta, pi and gamma are concatenated and passed to the creation of a ```CoordSystem``` class using the ```to_vector()``` method.

In [582]:
assert out_vec[-1][0] == EXT_IDX and out_vec[0][0] == SOL_IDX
profile_vec = np.concatenate([out_vec[:-1], EOS_VEC[np.newaxis]])
# profile = Profile.from_vector(profile_vec, is_numerical=is_numerical)
ext_vec = out_vec[-1][-N_ARGS_EXT:] # [theta, phi, gamma, x, y, z, s, e1, e2, b, u]
sket_pos = ext_vec[N_ARGS_PLANE:N_ARGS_PLANE + 3]# p_x, p_y, p_z 
sket_size = ext_vec[N_ARGS_PLANE + N_ARGS_TRANS - 1] # s
theta_phi_gamma = ext_vec[:N_ARGS_PLANE] # theta, phi, gamma
temp = np.concatenate([sket_pos, theta_phi_gamma])
temp.shape

(6,)

Then a ```CordSystem``` class is created from the translation and and orientation vector. This class is defined by the aforementioned parameters and as the purpose of this class is not completely clear yet, it will be discussed later. Finally the ```Extrude``` class is created by passing the ```Profile```, ```CoordSystem``` and the extrusion parameters operation type, extent type and the extrude distance in both directions. 

In [588]:
# sket_plane = CoordSystem.from_vector(temp)
ext_param = ext_vec[-N_ARGS_EXT_PARAM:] # e1, e2, b, u
#res = Extrude(profile, sket_plane, int(ext_param[2]), int(ext_param[3]), ext_param[0], ext_param[1], sket_pos, sket_size)

## Profile.from_vector()
The Extrude class wants to create a profile from the sketches. Therefore the ```Profile.from_vector()``` static class method is called on the ```profile_vec``` vector. This method extracts every loop a sketch/profile is made of and creates a list of loops a profile is made of. From every loop a ```Loop``` object is created.

In [559]:
all_loops = []
command = profile_vec[:, 0]
end_idx = command.tolist().index(EOS_IDX)
indices = np.where(command[:end_idx] == SOL_IDX)[0].tolist() + [end_idx]
for i in range(len(indices) - 1):
    loop_vec = profile_vec[indices[i]:indices[i + 1]]
    loop_vec = np.concatenate([loop_vec, EOS_VEC[np.newaxis]], axis=0)
    if loop_vec[0][0] == SOL_IDX and loop_vec[1][0] not in [SOL_IDX, EOS_IDX]:
        # all_loops.append(Loop.from_vector(loop_vec, is_numerical=is_numerical))
        print("Append new loop to all_loops")

loop_vec

Append new loop to all_loops


array([[  4.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  0., 223., 128.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  0., 223., 223.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  0., 128., 223.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  0., 128., 128.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  3.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
         -1.,  -1.,  -1.,  -1.,  -1.,  -1.]])

## Loop.from_vector()

The method first determines the starting point of the loop by iterating to the last end point of a command which will be the start point of the first command, as the elements form a loop.

In [560]:
all_curves = []
# find start point
for i in range(loop_vec.shape[0]):
    if loop_vec[i][0] == EOS_IDX:
        start_point = loop_vec[i - 1][1:3]
        break

for i in range(loop_vec.shape[0]):
    type = loop_vec[i][0]
    if type == SOL_IDX:
        continue
    elif type == EOS_IDX:
        break

    else:
        print("Append new curve: ", end="")
        curve = construct_curve_from_vector(loop_vec[i], start_point, is_numerical=is_numerical)
        start_point = loop_vec[i][1:3] # current curve's end_point serves as next curve's start_point
        
    #all_curves.append(curve)
        

Append new curve: Line
Append new curve: Line
Append new curve: Line
Append new curve: Line


## construct_curve_from_vector

In [561]:
def construct_curve_from_vector(vec, start_point, is_numerical=True):
    type = vec[0]
    if type == LINE_IDX:
        print("Line")
        #return Line.from_vector(vec, start_point, is_numerical=is_numerical)
    elif type == CIRCLE_IDX:
        print("Circle")
       # return Circle.from_vector(vec, start_point, is_numerical=is_numerical)
    elif type == ARC_IDX:
        print("Arc")
        #res = Arc.from_vector(vec, start_point, is_numerical=is_numerical)
       # if res is None: # for visualization purpose, replace illed arc with line
        #    return Line.from_vector(vec, start_point, is_numerical=is_numerical)
       # return res
    else:
        raise NotImplementedError("curve type not supported yet: command idx {}".format(vec[0]))

## Line/Circle/Arc.from_vector

There are classes for Line, Circle and Arc, which are defined by their respective parameters. Their implementation is trivial and is omitted now. But let's recap the findings.

- A CAD model is defined by a ```CADSequence```.
    - ```CADSequence``` is made of a python list of one or many ```Extrude``` classes.
    - ```CADSequence``` can determine the number of extrusions (and therefore the number of instances of the class ```Extrude```) by splitting the command sequence according to the extrusion command index (Index: 5). The CAD sequence is split into multiple extrusion sequences
- An ```Extrude``` is made of a ```Profile``` and a ```CoordSystem```
    - The ```Extrude``` constructor (from vector) class method basically just passess the particular extrusion sequence to the ```Profile``` class to create a profile
    - The ```Extrude``` class is made of a ```Profile``` and a ```CoordSystem``` class
- A ```Profile``` is a python list made of one or many ```Loop```'s
    - This class splits the extrusion command into the individual loops it is made of and passes the particular sequence to the particular class definition of the loop part
- The ```Loop``` class is a python list of one or many curves
- It first determines the start point of the first curve (from the endpoint of the last curve) and then passes the loop sequence to the particular Curve class
- Curves: ```Line```'s, ```Arc```'s, ```Circle```'s
    - These foundational building blocks are defined by their respective parameters.
 
Summarizing:

A **CAD Model** is defined by a ```CADSequence```, which is a list of ```Extrude```'s, each containing a ```CoordSystem``` and a ```Profile```, which is a list of ```Loop```'s, which is a list of curves, made of ```Line```'s, ```Arc```'s and ```Circle```'s.

## create_CAD()

This function starts with creating the first body using the the first extrusion (remember a ```CADSequence``` is just a list of ```Extrude``` classes) with the function ```create_by_extrude()```. Then in a for loop the next ```Extrude``` objects are created and combined according to the extrude operation.

### create_by_extrude()
This method takes an ```Extrude``` object and returns a Python OCC object.
- copy ```Profile``` for safety
- denormalize the ```Profile```, de- and normalization is another topic worth looking at
- Extract the origin of the previous plane
- Create a profile face from ```Profile``` and ```CoordSystem``` using ```create_profile_face()```
    - To create a profile face:
    - Set origin as ```gp_Pnt```
    - Get the normal of the plane (Easy by using theta and phi, which are Euler angles)
    - Sequentially reconstruct Points --> Curves --> Loops --> Profiles --> Exrusions using Python OCC library (library to create B-rep models, pretty complex)
    - These objects can the be written to a ```.step``` file

In [634]:
# Some geometry functions regarding the Euler angles
def rotate_by_y(vec, theta):
    mat = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    return np.dot(mat, vec)


def rotate_by_z(vec, phi):
    mat = np.array([[np.cos(phi), -np.sin(phi), 0],
                    [np.sin(phi), np.cos(phi), 0],
                    [0, 0, 1]])
    return np.dot(mat, vec)
    
def polar2cartesian(vec):
    """convert a vector in polar(spherical) coordinates to cartesian coordinates"""
    r = 1 if len(vec) == 2 else vec[2]
    theta, phi = vec[0], vec[1]
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return np.array([x, y, z])

In [635]:
a = np.array([1, 0, 0])
theta = np.pi / 2
phi = np.pi / 2
print(phi)
normal_3d = polar2cartesian([theta, phi])
normal_3d


1.5707963267948966


array([6.123234e-17, 1.000000e+00, 6.123234e-17])

## latent gan

Even though the generator starts with random noise, it learns to **produce realistic latent vectors** through its interaction with the discriminator.

ChatGPT summary of how the GAN works (after some prompting):

## **1. The GAN’s Adversarial Training Process**
The generator \( G \) and discriminator \( D \) are trained **simultaneously** in an adversarial manner. Here’s how it works:

1. **Generator's Role**:
   - The generator G takes random noise and outputs a latent vector z
   - At the beginning of training, the generator produces completely random outputs because its weights are randomly initialized.

2. **Discriminator's Role**:
   - The discriminator D takes a latent vector z (either real z_real or fake z_fake) and outputs a score D(z):
     - \( D(z) \) is **high** for real latent vectors z_real (from the autoencoder).
     - \( D(z) \) is **low** for fake latent vectors z_gen (from the generator).

3. **Adversarial Objective**:
   - The discriminator \( D \) tries to **maximize** the difference between real and fake scores:
   - The generator \( G \) tries to **fool** the discriminator by producing fake latent vectors z_gen that look like real ones. The generator’s loss is:
     - This means the generator tries to **minimize** the discriminator’s score for fake latent vectors, essentially tricking the discriminator into believing z_gen are real.

---

## **2. How the Generator Learns to Fool the Discriminator**
Even though the generator starts with random noise, it gradually learns to produce realistic latent vectors through **gradient-based optimization**.

Here’s how:

1. **Discriminator Backpropagation**:
   - During training, the discriminator \( D \) is updated to distinguish real latent vectors \( z_{\text{real}} \) from fake latent vectors \( z_{\text{gen}} \).
   - The discriminator’s gradients flow backward to improve its ability to classify real and fake vectors.

2. **Generator Backpropagation**:
   - The generator \( G \) does not directly see the real latent vectors. Instead, it **receives feedback** from the discriminator.
   - Specifically, the gradients of the discriminator’s output \( D(z_{\text{gen}}) \) are backpropagated **through the generator** to update its weights.
   - Intuitively:
     - If D(z_gen) is low (discriminator says "fake"), the generator gets a **strong gradient signal** to adjust its weights.
     - The generator updates its parameters so that the next batch of z_gen is closer to the real latent vectors z_real.

3. **Iterative Improvement**:
   - Over many iterations, the generator \( G \) learns to produce latent vectors z_gen that are indistinguishable from z_real because:
     - The discriminator keeps improving its ability to tell real from fake.
     - The generator keeps improving its outputs to fool the discriminator.

---

## **3. The Role of Noise Input**
The random noise serves as a **seed** for the generator to produce diverse outputs. Without noise:
- The generator might always produce the same output (collapse issue).
- Random noise ensures that the generator can produce a variety of latent vectors z_gen.

The generator learns to **map the noise distribution** to the real latent space distribution p(z_real).

---

## **4. The Big Picture**
To summarize the generator’s learning process:
1. The generator \( G \) starts with random weights and outputs garbage latent vectors z_gen.
2. The discriminator \( D \) learns to classify real latent vectors z_real and fake ones z_gen.
3. The generator receives gradients from the discriminator, telling it how to adjust its weights to produce better latent vectors.
4. Over time, the generator learns to transform random noise into realistic latent vectors z_gen that match the distribution of z_real.

Once training is complete:
- The generator can take random noise as input and output new latent vectors z_gen.
- These generated latent vectors can be passed to the **autoencoder’s decoder** to produce new CAD sequences.


# PointNet

To train **PointNet++** to project a point cloud into the same latent space as your CAD model autoencoder, the goal is to ensure that the **PointNet++ encoder** produces latent vectors that align with the latent vectors \( c \) generated by the **pre-trained autoencoder**. Here's a step-by-step process:

---

### 1. **Overview of the Problem**
- You already have a pre-trained autoencoder that maps CAD command sequences to a **256-dimensional latent space** \( c \).
- The PointNet++ encoder will process **point clouds** (e.g., 3D scanned data) and map them to the **same latent space** \( c \).
- To achieve this, you need to train PointNet++ so that its latent vectors **match the latent vectors** produced by the autoencoder.

---

### 2. **Data Preparation**
1. **Input Data**: For each CAD model \( M \), you need:
   - Its **point cloud representation** \( P \) (e.g., sampled points from the 3D surface of the CAD model).
   - Its corresponding **latent vector \( c \)** produced by the autoencoder (already trained).

   This gives you paired data:  
   \[
   (P, c)
   \]  
   where \( P \) is the point cloud, and \( c \) is the target latent vector.

2. **Point Cloud Sampling**:
   - Ensure the point clouds are consistent (e.g., uniformly sampled points from the CAD model surface).
   - Use a fixed number of points (e.g., 1024 or 2048 points) for all point clouds to standardize input to PointNet++.

---

### 3. **Architecture Setup**
1. **Pre-trained Autoencoder**:
   - The autoencoder is fixed (frozen weights). It acts as a **reference** for the target latent space \( c \).

2. **PointNet++ Encoder**:
   - Use the PointNet++ architecture to process the point cloud \( P \) and output a latent vector \( \hat{c} \) of size 256 (matching the autoencoder's latent space).

   Architecture:
   \[
   P \rightarrow \text{PointNet++ Encoder} \rightarrow \hat{c}.
   \]

3. **Loss Function**:
   - Use a **regression loss** to minimize the difference between the latent vector \( \hat{c} \) produced by PointNet++ and the latent vector \( c \) from the autoencoder:
     \[
     L = \| c - \hat{c} \|^2
     \]
   - This ensures that the PointNet++ encoder learns to produce latent vectors that align with the autoencoder's latent space.

NEXT: 
- MWE not didactic but input --> model --> output (Basically implement the reconstruct method and play around, f.e. what happens if for b or u a parameter other than the eligable are predicted?)
- I guess look at PointNet? and PointNet++?
- SET UP ROADMAP FOR END GOAL
- END GOAL: Have a complete Pipeline of: Input PC --> PointNet++ --> DeepCAD Decoder --> CAD object in CAD program

In [636]:
vec = np.array([0,0])
phi = np.arctan(vec[1] / (vec[0] + 1e-15))

In [637]:
phi

0.0

In [643]:
import glob

out_paths = sorted(glob.glob(os.path.join(src_dir, "*.{}".format("h5"))))

In [641]:
src_dir = "../DeepCAD/proj_log/pretrained/results/test_1000"
os.path.exists(src_dir)

True

In [645]:
print(len(out_paths))

8052


In [648]:
save_dir = src_dir + "_step"
save_dir

'../DeepCAD/proj_log/pretrained/results/test_1000_step'